// Mapping of normalized country names to TopoJSON numeric IDs
// TopoJSON uses ISO 3166-1 numeric codes

export const countryNameToId: Record<string, string> = {
  afghanistan: "004",
  albania: "008",
  algeria: "012",
  andorra: "020",
  angola: "024",
  antigua_and_barbuda: "028",
  argentina: "032",
  armenia: "051",
  australia: "036",
  austria: "040",
  azerbaijan: "031",
  bahamas: "044",
  bahrain: "048",
  bangladesh: "050",
  barbados: "052",
  belarus: "112",
  belgium: "056",
  belize: "084",
  benin: "204",
  bhutan: "064",
  bolivia: "068",
  bosnia_and_herzegovina: "070",
  botswana: "072",
  brazil: "076",
  brunei: "096",
  bulgaria: "100",
  burkina_faso: "854",
  burundi: "108",
  cambodia: "116",
  cameroon: "120",
  canada: "124",
  cape_verde: "132",
  central_african_republic: "140",
  chad: "148",
  chile: "152",
  china: "156",
  colombia: "170",
  comoros: "174",
  congo: "178",
  costa_rica: "188",
  croatia: "191",
  cuba: "192",
  cyprus: "196",
  czech_republic: "203",
  czechia: "203",
  democratic_republic_of_the_congo: "180",
  dr_congo: "180",
  denmark: "208",
  djibouti: "262",
  dominica: "212",
  dominican_republic: "214",
  east_timor: "626",
  timor_leste: "626",
  ecuador: "218",
  egypt: "818",
  el_salvador: "222",
  equatorial_guinea: "226",
  eritrea: "232",
  estonia: "233",
  eswatini: "748",
  swaziland: "748",
  ethiopia: "231",
  fiji: "242",
  finland: "246",
  france: "250",
  gabon: "266",
  gambia: "270",
  georgia: "268",
  germany: "276",
  ghana: "288",
  greece: "300",
  greenland: "304",
  grenada: "308",
  guatemala: "320",
  guinea: "324",
  guinea_bissau: "624",
  guyana: "328",
  haiti: "332",
  honduras: "340",
  hungary: "348",
  iceland: "352",
  india: "356",
  indonesia: "360",
  iran: "364",
  iraq: "368",
  ireland: "372",
  israel: "376",
  italy: "380",
  ivory_coast: "384",
  cote_divoire: "384",
  jamaica: "388",
  japan: "392",
  jordan: "400",
  kazakhstan: "398",
  kenya: "404",
  kiribati: "296",
  north_korea: "408",
  south_korea: "410",
  korea: "410",
  kosovo: "-99",
  kuwait: "414",
  kyrgyzstan: "417",
  laos: "418",
  latvia: "428",
  lebanon: "422",
  lesotho: "426",
  liberia: "430",
  libya: "434",
  liechtenstein: "438",
  lithuania: "440",
  luxembourg: "442",
  madagascar: "450",
  malawi: "454",
  malaysia: "458",
  maldives: "462",
  mali: "466",
  malta: "470",
  marshall_islands: "584",
  mauritania: "478",
  mauritius: "480",
  mexico: "484",
  micronesia: "583",
  moldova: "498",
  monaco: "492",
  mongolia: "496",
  montenegro: "499",
  morocco: "504",
  mozambique: "508",
  myanmar: "104",
  burma: "104",
  namibia: "516",
  nauru: "520",
  nepal: "524",
  netherlands: "528",
  new_zealand: "554",
  nicaragua: "558",
  niger: "562",
  nigeria: "566",
  north_macedonia: "807",
  macedonia: "807",
  norway: "578",
  oman: "512",
  pakistan: "586",
  palau: "585",
  palestine: "275",
  panama: "591",
  papua_new_guinea: "598",
  paraguay: "600",
  peru: "604",
  philippines: "608",
  poland: "616",
  portugal: "620",
  puerto_rico: "630",
  qatar: "634",
  romania: "642",
  russia: "643",
  rwanda: "646",
  saint_kitts_and_nevis: "659",
  saint_lucia: "662",
  saint_vincent_and_the_grenadines: "670",
  samoa: "882",
  san_marino: "674",
  sao_tome_and_principe: "678",
  saudi_arabia: "682",
  senegal: "686",
  serbia: "688",
  seychelles: "690",
  sierra_leone: "694",
  singapore: "702",
  slovakia: "703",
  slovenia: "705",
  solomon_islands: "090",
  somalia: "706",
  somaliland: "-98",
  south_africa: "710",
  south_sudan: "728",
  spain: "724",
  sri_lanka: "144",
  sudan: "729",
  suriname: "740",
  sweden: "752",
  switzerland: "756",
  syria: "760",
  taiwan: "158",
  tajikistan: "762",
  tanzania: "834",
  thailand: "764",
  togo: "768",
  tonga: "776",
  trinidad_and_tobago: "780",
  tunisia: "788",
  turkey: "792",
  turkmenistan: "795",
  tuvalu: "798",
  uganda: "800",
  ukraine: "804",
  united_arab_emirates: "784",
  uae: "784",
  united_kingdom: "826",
  uk: "826",
  united_states: "840",
  usa: "840",
  us: "840",
  uruguay: "858",
  uzbekistan: "860",
  vanuatu: "548",
  vatican: "336",
  venezuela: "862",
  vietnam: "704",
  yemen: "887",
  zambia: "894",
  zimbabwe: "716",
};

// Reverse mapping: ID to normalized name
export const countryIdToName: Record<string, string> = Object.entries(
  countryNameToId
).reduce(
  (acc, [name, id]) => {
    // Only keep the first (canonical) name for each ID
    if (!acc[id]) {
      acc[id] = name;
    }
    return acc;
  },
  {} as Record<string, string>
);

// Display names for countries
export const countryDisplayNames: Record<string, string> = {
  france: "France",
  italy: "Italy",
  japan: "Japan",
  united_states: "United States",
  usa: "United States",
  us: "United States",
  united_kingdom: "United Kingdom",
  uk: "United Kingdom",
  germany: "Germany",
  spain: "Spain",
  portugal: "Portugal",
  greece: "Greece",
  netherlands: "Netherlands",
  belgium: "Belgium",
  switzerland: "Switzerland",
  austria: "Austria",
  sweden: "Sweden",
  norway: "Norway",
  denmark: "Denmark",
  finland: "Finland",
  iceland: "Iceland",
  ireland: "Ireland",
  poland: "Poland",
  czech_republic: "Czech Republic",
  czechia: "Czech Republic",
  hungary: "Hungary",
  croatia: "Croatia",
  slovenia: "Slovenia",
  slovakia: "Slovakia",
  romania: "Romania",
  bulgaria: "Bulgaria",
  serbia: "Serbia",
  montenegro: "Montenegro",
  albania: "Albania",
  north_macedonia: "North Macedonia",
  macedonia: "North Macedonia",
  bosnia_and_herzegovina: "Bosnia and Herzegovina",
  estonia: "Estonia",
  latvia: "Latvia",
  lithuania: "Lithuania",
  ukraine: "Ukraine",
  belarus: "Belarus",
  russia: "Russia",
  turkey: "Turkey",
  china: "China",
  india: "India",
  thailand: "Thailand",
  vietnam: "Vietnam",
  indonesia: "Indonesia",
  malaysia: "Malaysia",
  singapore: "Singapore",
  philippines: "Philippines",
  south_korea: "South Korea",
  korea: "South Korea",
  taiwan: "Taiwan",
  australia: "Australia",
  new_zealand: "New Zealand",
  canada: "Canada",
  mexico: "Mexico",
  brazil: "Brazil",
  argentina: "Argentina",
  chile: "Chile",
  peru: "Peru",
  colombia: "Colombia",
  egypt: "Egypt",
  morocco: "Morocco",
  south_africa: "South Africa",
  kenya: "Kenya",
  tanzania: "Tanzania",
  ethiopia: "Ethiopia",
  nigeria: "Nigeria",
  ghana: "Ghana",
  senegal: "Senegal",
  united_arab_emirates: "United Arab Emirates",
  uae: "United Arab Emirates",
  saudi_arabia: "Saudi Arabia",
  israel: "Israel",
  jordan: "Jordan",
  lebanon: "Lebanon",
  iran: "Iran",
  iraq: "Iraq",
  pakistan: "Pakistan",
  afghanistan: "Afghanistan",
  nepal: "Nepal",
  sri_lanka: "Sri Lanka",
  bangladesh: "Bangladesh",
  myanmar: "Myanmar",
  burma: "Myanmar",
  cambodia: "Cambodia",
  laos: "Laos",
  mongolia: "Mongolia",
  kazakhstan: "Kazakhstan",
  uzbekistan: "Uzbekistan",
  papua_new_guinea: "Papua New Guinea",
  fiji: "Fiji",
  cuba: "Cuba",
  jamaica: "Jamaica",
  dominican_republic: "Dominican Republic",
  haiti: "Haiti",
  puerto_rico: "Puerto Rico",
  costa_rica: "Costa Rica",
  panama: "Panama",
  guatemala: "Guatemala",
  honduras: "Honduras",
  el_salvador: "El Salvador",
  nicaragua: "Nicaragua",
  belize: "Belize",
  ecuador: "Ecuador",
  bolivia: "Bolivia",
  paraguay: "Paraguay",
  uruguay: "Uruguay",
  venezuela: "Venezuela",
  guyana: "Guyana",
  suriname: "Suriname",
  algeria: "Algeria",
  tunisia: "Tunisia",
  libya: "Libya",
  sudan: "Sudan",
  south_sudan: "South Sudan",
};

export function getDisplayName(normalizedName: string): string {
  return countryDisplayNames[normalizedName] ||
    normalizedName.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

export function getCountryId(normalizedName: string): string | undefined {
  return countryNameToId[normalizedName];
}

export function normalizeCountryName(name: string): string {
  return name.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z_]/g, '');
}
